-- GENERATED by scripts/build-data.mjs — DO NOT EDIT BY HAND.
-- Source: data/planner.json (SimpleArmory).

SAMountsRouteData = {
  {
    title = "Start in ",
    notes = "Set Hearthstone to Faction Capital",
    capital = true,
    startStep = true,
    steps = {
      {
        title = "Portal to Uldum",
        steps = {
          {
            title = "Run Vortex Pinnacle (Dungeon)",
            type = "Dungeon",
            bosses = {
              {
                ID = 395,
                mount = "Drake of the North Wind",
                name = "Altairus",
                itemId = 63040,
                spellId = 88742,
                icon = "inv_misc_stormdragonpale",
                epic = true,
                note = "You can run Heroic once per day and up to 10x Normal an hour",
              },
            },
          },
          {
            title = "Run Throne of the Four Winds (Raid)",
            type = "Raid",
            bosses = {
              {
                ID = 396,
                mount = "Drake of the South Wind",
                name = "Al'akir",
                itemId = 63041,
                spellId = 88744,
                icon = "inv_misc_stormdragonpurple",
                epic = true,
              },
            },
          },
          {
            title = "Fly to Silithus",
            steps = {
              {
                title = "Run Ahn'Qiraj (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 117,
                    mount = "Blue Qiraji Crystal",
                    name = "Trash",
                    itemId = 21218,
                    spellId = 25953,
                    icon = "inv_misc_qirajicrystal_04",
                    epic = false,
                  },
                  {
                    ID = 120,
                    mount = "Green Qiraji Crystal",
                    name = "Trash",
                    itemId = 21323,
                    spellId = 26056,
                    icon = "inv_misc_qirajicrystal_03",
                    epic = false,
                  },
                  {
                    ID = 119,
                    mount = "Yellow Qiraji Crystal",
                    name = "Trash",
                    itemId = 21324,
                    spellId = 26055,
                    icon = "inv_misc_qirajicrystal_01",
                    epic = false,
                  },
                  {
                    ID = 118,
                    mount = "Red Qiraji Crystal",
                    name = "Trash",
                    itemId = 21321,
                    spellId = 26054,
                    icon = "inv_misc_qirajicrystal_02",
                    epic = false,
                  },
                },
              },
            },
          },
          {
            title = "Fly to Dustwallow Marsh",
            steps = {
              {
                title = "Run Onyxia (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 349,
                    mount = "Onyxian Drake",
                    name = "Onyxia",
                    itemId = 49636,
                    spellId = 69395,
                    icon = "achievement_boss_onyxia",
                    epic = true,
                  },
                },
              },
            },
          },
        },
      },
      {
        title = "and Portal to Northrend Dalaran",
        capital = true,
        steps = {
          {
            title = "Fly to Icecrown",
            steps = {
              {
                title = "Run Icecrown Citadel (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 363,
                    mount = "Invincible's Reins",
                    name = "The Lich King",
                    itemId = 50818,
                    spellId = 72286,
                    icon = "ability_mount_pegasus",
                    epic = true,
                    note = "Heroic 25 only",
                  },
                },
              },
            },
          },
          {
            title = "Fly to Wintergrasp",
            steps = {
              {
                title = "Run Vault of Archavon (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 286,
                    mount = "Grand Black War Mammoth",
                    name = "Koralon",
                    itemId = 43959,
                    icon = "ability_mount_mammoth_black",
                    epic = true,
                    isAlliance = true,
                  },
                  {
                    ID = 286,
                    mount = "Grand Black War Mammoth",
                    name = "Toravon",
                    itemId = 43959,
                    icon = "ability_mount_mammoth_black",
                    epic = true,
                    isAlliance = true,
                  },
                  {
                    ID = 286,
                    mount = "Grand Black War Mammoth",
                    name = "Archavon",
                    itemId = 43959,
                    icon = "ability_mount_mammoth_black",
                    epic = true,
                    isAlliance = true,
                  },
                  {
                    ID = 286,
                    mount = "Grand Black War Mammoth",
                    name = "Emalon",
                    itemId = 43959,
                    icon = "ability_mount_mammoth_black",
                    epic = true,
                    isAlliance = true,
                  },
                  {
                    ID = 287,
                    mount = "Grand Black War Mammoth",
                    name = "Koralon",
                    itemId = 44083,
                    icon = "ability_mount_mammoth_black",
                    epic = true,
                    isHorde = true,
                  },
                  {
                    ID = 287,
                    mount = "Grand Black War Mammoth",
                    name = "Toravon",
                    itemId = 44083,
                    icon = "ability_mount_mammoth_black",
                    epic = true,
                    isHorde = true,
                  },
                  {
                    ID = 287,
                    mount = "Grand Black War Mammoth",
                    name = "Archavon",
                    itemId = 44083,
                    icon = "ability_mount_mammoth_black",
                    epic = true,
                    isHorde = true,
                  },
                  {
                    ID = 287,
                    mount = "Grand Black War Mammoth",
                    name = "Emalon",
                    itemId = 44083,
                    icon = "ability_mount_mammoth_black",
                    epic = true,
                    isHorde = true,
                  },
                },
              },
            },
          },
          {
            title = "Fly to Coldarra",
            steps = {
              {
                title = "Run Eye of Eternity (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 246,
                    mount = "Azure Drake",
                    name = "Malygos",
                    itemId = 43952,
                    spellId = 59567,
                    icon = "ability_mount_drake_azure",
                    epic = true,
                  },
                  {
                    ID = 247,
                    mount = "Blue Drake",
                    name = "Malygos",
                    itemId = 43953,
                    spellId = 59568,
                    icon = "ability_mount_drake_blue",
                    epic = true,
                  },
                },
              },
            },
          },
          {
            title = "Fly to Wyrmrest Temple",
            steps = {
              {
                title = "Run Obsidian Sanctum (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 253,
                    mount = "Black Drake",
                    name = "Sartharion",
                    itemId = 43986,
                    spellId = 59650,
                    icon = "ability_mount_drake_twilight",
                    epic = true,
                    note = "10 Man, All Purple Dragons Up",
                  },
                  {
                    ID = 250,
                    mount = "Twilight Drake",
                    name = "Sartharion",
                    itemId = 43954,
                    spellId = 59571,
                    icon = "ability_mount_drake_twilight",
                    epic = true,
                    note = "25 Man, All Purple Dragons Up",
                  },
                },
              },
            },
          },
          {
            title = "Fly to Howling Fjord",
            steps = {
              {
                title = "Run Utgarde Pinnacle (Dungeon)",
                type = "Dungeon",
                bosses = {
                  {
                    ID = 264,
                    mount = "Blue Proto-Drake",
                    name = "Skadi",
                    itemId = 44151,
                    spellId = 59996,
                    icon = "ability_mount_drake_proto",
                    epic = true,
                    note = "Heroic only",
                  },
                },
              },
            },
          },
          {
            title = "Fly to Storm Peaks",
            steps = {
              {
                title = "Run Ulduar (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 304,
                    mount = "Mimiron's Head",
                    name = "Yogg-Saron",
                    itemId = 45693,
                    spellId = 63796,
                    icon = "inv_misc_enggizmos_03",
                    epic = true,
                    note = "Requires no watchers up",
                  },
                },
              },
            },
          },
        },
      },
      {
        title = "",
        capital = true,
        steps = {
          {
            title = "Portal to Hyjal",
            steps = {
              {
                title = "Run Firelands on both Normal and Heroic (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 425,
                    mount = "Flametalon of Alysrazor",
                    name = "Alysrazor",
                    itemId = 71665,
                    spellId = 101542,
                    icon = "ability_mount_fireravengodmount",
                    epic = true,
                  },
                  {
                    ID = 415,
                    mount = "Egg of Millagazor",
                    name = "Ragnaros",
                    itemId = 69224,
                    spellId = 97493,
                    icon = "inv_misc_orb_05",
                    epic = true,
                  },
                },
              },
            },
          },
        },
      },
      {
        title = "",
        capital = true,
        steps = {
          {
            title = "Portal to Caverns of Time",
            steps = {
              {
                title = "Run Culling of Stratholme (Dungeon)",
                type = "Dungeon",
                bosses = {
                  {
                    ID = 248,
                    mount = "Bronze Drake",
                    name = "Infinite Corruptor",
                    itemId = 43951,
                    spellId = 59569,
                    icon = "ability_mount_drake_bronze",
                    epic = true,
                    note = "Heroic only. Timed run",
                  },
                },
              },
              {
                title = "Run Dragon Soul (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 445,
                    mount = "Experiment 12-B",
                    name = "Ultraxion",
                    itemId = 78919,
                    spellId = 110039,
                    icon = "ability_mount_drake_twilight",
                    epic = true,
                  },
                  {
                    ID = 442,
                    mount = "Blazing Drake",
                    name = "Deathwing",
                    itemId = 77067,
                    spellId = 107842,
                    icon = "ability_mount_drake_red",
                    epic = true,
                  },
                  {
                    ID = 444,
                    mount = "Life-Binder's Handmaiden",
                    name = "Deathwing",
                    itemId = 77069,
                    spellId = 107845,
                    icon = "ability_mount_drake_red",
                    epic = true,
                    note = "Heroic only",
                  },
                },
              },
            },
          },
        },
      },
      {
        title = "",
        capital = true,
        steps = {
          {
            title = "Portal to Deepholm",
            steps = {
              {
                title = "Run Stonecore (Dungeon)",
                type = "Dungeon",
                bosses = {
                  {
                    ID = 397,
                    mount = "Vitreous Stone Drake",
                    name = "Slabhide",
                    itemId = 63043,
                    spellId = 88746,
                    icon = "inv_misc_stonedragonblue",
                    epic = true,
                    note = "You can run Heroic once per day and up to 10x Normal an hour",
                  },
                },
              },
              {},
            },
          },
        },
      },
      {
        title = "and Portal to Shattrath",
        capital = true,
        steps = {
          {
            title = "Fly to Auchindoun",
            steps = {
              {
                title = "Run Sethekk Halls (Dungeon)",
                type = "Dungeon",
                bosses = {
                  {
                    ID = 185,
                    mount = "Raven Lord",
                    name = "Anzu",
                    itemId = 32768,
                    spellId = 41252,
                    icon = "inv-mount_raven_54",
                    epic = true,
                    note = "Heroic only",
                  },
                },
              },
            },
          },
          {
            title = "Fly to Netherstorm",
            steps = {
              {
                title = "Run Tempest Keep (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 183,
                    mount = "Ashes of Al'ar",
                    name = "Kael'thas",
                    itemId = 32458,
                    spellId = 40192,
                    icon = "inv_misc_summerfest_brazierorange",
                    epic = true,
                  },
                },
              },
            },
          },
          {
            title = "Fly to Shattrath",
            steps = {
              {
                title = "Portal to Isle of Quel'Danas",
                steps = {
                  {
                    title = "Run Magister's Terrace (Dungeon)",
                    type = "Dungeon",
                    bosses = {
                      {
                        ID = 213,
                        mount = "Swift White Hawkstrider",
                        name = "Kael'thas",
                        itemId = 35513,
                        spellId = 46628,
                        icon = "ability_mount_cockatricemountelite_white",
                        epic = true,
                        note = "Heroic only",
                      },
                    },
                  },
                  {
                    title = "Fly to Ghostlands",
                    steps = {
                      {
                        title = "Run Zul'Aman (Dungeon)",
                        type = "Dungeon",
                        bosses = {
                          {
                            ID = 419,
                            mount = "Amani Battle Bear",
                            name = "Timed Reward",
                            itemId = 69747,
                            spellId = 98204,
                            icon = "ability_druid_challangingroar",
                            epic = true,
                            note = "Heroic only",
                          },
                        },
                      },
                    },
                  },
                  {
                    title = "Fly to Eastern Plaguelands",
                    steps = {
                      {
                        title = "Run Stratholme (Dungeon)",
                        type = "Dungeon",
                        bosses = {
                          {
                            ID = 69,
                            mount = "Deathcharger's Reins",
                            name = "Rivendare",
                            itemId = 13335,
                            spellId = 17481,
                            icon = "ability_mount_undeadhorse",
                            epic = true,
                          },
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
      {
        title = "",
        capital = true,
        steps = {
          {
            title = "Fly to Stranglethorn Vale ",
            steps = {
              {
                title = "Fly to Deadwind Pass",
                steps = {
                  {
                    title = "Run Karazhan (Raid)",
                    type = "Raid",
                    bosses = {
                      {
                        ID = 168,
                        mount = "Fiery Warhorse's Reins",
                        name = "Attumen",
                        itemId = 30480,
                        spellId = 36702,
                        icon = "ability_mount_dreadsteed",
                        epic = true,
                      },
                    },
                  },
                  {
                    title = "Run Return to Karazhan (Dungeon)",
                    type = "WeeklyDungeon",
                    bosses = {
                      {
                        ID = 875,
                        mount = "Midnight's Eternal Reins",
                        name = "Attumen",
                        itemId = 142236,
                        spellId = 229499,
                        icon = "inv_skeletalwarhorse_black",
                        epic = true,
                        note = "Mythic only",
                      },
                      {
                        ID = 883,
                        mount = "Smoldering Ember Wyrm",
                        name = "Nightbane",
                        itemId = 142552,
                        spellId = 231428,
                        icon = "inv_nightbane2mount",
                        epic = true,
                        note = "Mythic only, Timed Reward",
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
      {
        title = "Fly to Stranglethorn Vale",
        steps = {
          {
            title = "Run Zul'Gurub (Dungeon)",
            type = "Dungeon",
            bosses = {
              {
                ID = 411,
                mount = "Swift Zulian Panther",
                name = "Kilnara",
                itemId = 68824,
                spellId = 96499,
                icon = "ability_mount_blackpanther",
                epic = true,
                note = "Heroic only",
              },
              {
                ID = 410,
                mount = "Armored Razzashi Raptor",
                name = "Mandokir",
                itemId = 68823,
                spellId = 96491,
                icon = "ability_mount_raptor",
                epic = true,
                note = "Heroic only",
              },
            },
          },
        },
      },
      {
        title = "and Portal to Jade Forest",
        capital = true,
        steps = {
          {
            title = "Kill Galleon (World Boss)",
            type = "Raid",
            bosses = {
              {
                ID = 515,
                mount = "Son of Galleon's Saddle",
                name = "Galleon",
                itemId = 89783,
                spellId = 130965,
                icon = "inv_mushanbeastmount",
                epic = true,
                note = "Mount is bonus rollable",
              },
            },
          },
        },
      },
      {
        title = "Fly to Kun-Lai Summit",
        steps = {
          {
            title = "Kill Sha of Anger (World Boss)",
            type = "Raid",
            bosses = {
              {
                ID = 473,
                mount = "Reins of the Heavenly Onyx Cloud Serpent",
                name = "Sha of Anger",
                itemId = 87771,
                spellId = 127158,
                icon = "inv_pandarenserpentgodmount_black",
                epic = true,
                note = "Mount is bonus rollable",
              },
            },
          },
        },
      },
      {
        title = "Fly to Isle of Giants",
        steps = {
          {
            title = "Kill Oondasta (World Boss)",
            type = "Raid",
            bosses = {
              {
                ID = 533,
                mount = "Reins of the Cobalt Primordial Direhorn",
                name = "Oondasta",
                itemId = 94228,
                spellId = 138423,
                icon = "ability_mount_triceratopsmount_blue",
                epic = true,
                note = "Mount is bonus rollable",
              },
            },
          },
        },
      },
      {
        title = "Fly to Kun-Lai Summit",
        steps = {
          {
            title = "Run Mogu'shan Vaults (Raid)",
            type = "Raid",
            bosses = {
              {
                ID = 478,
                mount = "Reins of the Astral Cloud Serpent",
                name = "Elegon",
                itemId = 87777,
                spellId = 127170,
                icon = "inv_celestialserpentmount",
                epic = true,
              },
            },
          },
        },
      },
      {
        title = "and Portal to Jade Forest",
        capital = true,
        steps = {
          {
            title = "Portal to Isle of Thunder",
            steps = {
              {
                title = "Kill Nalak (World Boss)",
                type = "Raid",
                bosses = {
                  {
                    ID = 542,
                    mount = "Reins of the Thundering Cobalt Cloud Serpent",
                    name = "Nalak",
                    itemId = 95057,
                    spellId = 139442,
                    icon = "inv_pandarenserpentmount_lightning_blue",
                    epic = true,
                    note = "Mount is bonus rollable",
                  },
                },
              },
              {
                title = "Run Throne of Thunder (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 531,
                    mount = "Spawn of Horridon",
                    name = "Horridon",
                    itemId = 93666,
                    spellId = 136471,
                    icon = "ability_mount_triceratopsmount",
                    epic = true,
                    note = "Normal/Heroic",
                  },
                  {
                    ID = 543,
                    mount = "Clutch of Ji-Kun",
                    name = "Ji-Kun",
                    itemId = 95059,
                    spellId = 139448,
                    icon = "achievement_boss_ji-kun",
                    epic = true,
                    note = "Normal/Heroic",
                  },
                },
              },
            },
          },
        },
      },
      {
        title = "Fly to Vale of the Eternal Blossoms",
        steps = {
          {
            title = "Run Siege of Orgrimmar (Raid)",
            type = "Raid",
            bosses = {
              {
                ID = 559,
                mount = "Kor'kron Juggernaut",
                name = "Garrosh Hellscream",
                itemId = 104253,
                spellId = 148417,
                icon = "inv_mount_hordescorpiong",
                epic = true,
                note = "Mythic only",
              },
            },
          },
        },
      },
      {
        title = "Use Garrison Hearthstone",
        notes = "Must Have Garrison Unlocked",
        steps = {
          {
            title = "Fly to Spires of Arak",
            steps = {
              {
                title = "Kill Rukhmar (World Boss)",
                type = "Raid",
                bosses = {
                  {
                    ID = 634,
                    mount = "Solar Spirehawk",
                    name = "Rukhmar",
                    itemId = 116771,
                    spellId = 171828,
                    icon = "inv_helm_suncrown_d_01",
                    epic = true,
                    note = "Mount is NOT bonus rollable",
                  },
                },
              },
            },
          },
          {
            title = "Fly to Tanaan Jungle",
            notes = "Portal in Ashran",
            steps = {
              {
                title = "Run Hellfire Citadel (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 751,
                    mount = "Felsteel Annihilator",
                    name = "Archimonde",
                    itemId = 123890,
                    spellId = 182912,
                    icon = "ability_mount_felreavermount",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
            },
          },
          {
            title = "Fly to Gorgrond",
            steps = {
              {
                title = "Run Blackrock Foundry (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 613,
                    mount = "Ironhoof Destroyer",
                    name = "Blackhand",
                    itemId = 116660,
                    spellId = 171621,
                    icon = "inv_ironhordeclefthoof",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
            },
          },
        },
      },
      {
        title = "Heartstone to Dalaran",
        steps = {
          {
            title = "Fly to Suramar",
            steps = {
              {
                title = "Run Nighthold (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 791,
                    mount = "Living Infernal Core",
                    name = "Gul'dan",
                    itemId = 137574,
                    spellId = 213134,
                    icon = "inv_infernalmountgreen",
                    epic = true,
                    note = "Normal/Heroic/Mythic.",
                  },
                  {
                    ID = 633,
                    mount = "Fiendish Hellfire Core",
                    name = "Gul'dan",
                    itemId = 137575,
                    spellId = 171827,
                    icon = "inv_infernalmountred",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
            },
          },
        },
      },
      {
        title = "Fly to Broken Shore",
        steps = {
          {
            title = "Hearthstone to Dalaran",
            steps = {
              {
                title = "Run Tomb of Sargeras (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 899,
                    mount = "Abyss Worm",
                    name = "Mistress Sassz'ine",
                    itemId = 143643,
                    spellId = 232519,
                    icon = "inv_serpentmount_green",
                    epic = true,
                    note = "LFR/Normal/Heroic/Mythic",
                  },
                },
              },
            },
          },
        },
      },
      {
        title = "Hearthstone to Dalaran",
        steps = {
          {
            title = "Portal to Argus",
            steps = {
              {
                title = "Portal to Antoran Wastes",
                steps = {
                  {
                    title = "Run Antorus, the Burning Throne (Raid)",
                    type = "Raid",
                    bosses = {
                      {
                        ID = 971,
                        mount = "Antoran Charhound",
                        name = "Felhounds of Sargeras",
                        itemId = 152816,
                        spellId = 253088,
                        icon = "inv_felhound3_shadow_fire",
                        epic = true,
                        note = "LFR/Normal/Heroic/Mythic",
                      },
                      {
                        ID = 954,
                        mount = "Shackled Ur'zul",
                        name = "Argus the Unmaker",
                        itemId = 152789,
                        spellId = 243651,
                        icon = "inv_soulhoundmount_blue",
                        epic = true,
                        note = "Mythic only",
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
      {
        title = "",
        capital = true,
        steps = {
          {
            title = "Teleport to Zandalar / Kul'Tiras",
            steps = {
              {
                title = "Run Battle of Dazar'alor (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 1217,
                    mount = "G.M.O.D.",
                    name = "High Tinker Mekkatorque",
                    itemId = 166518,
                    spellId = 289083,
                    icon = "achievement_dungeon_coinoperatedcrowdpummeler",
                    epic = true,
                    note = "LFR (Jaina)/Normal/Heroic/Mythic",
                  },
                  {
                    ID = 1219,
                    mount = "Glacial Tidestorm",
                    name = "Jaina Proudmoore",
                    itemId = 166705,
                    spellId = 289555,
                    icon = "spell_frost_summonwaterelemental_2",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
            },
          },
          {
            title = "Walk to Tiragarde Sound",
            steps = {
              {
                title = "Run Freehold (Dungeon)",
                type = "WeeklyDungeon",
                bosses = {
                  {
                    ID = 995,
                    mount = "Sharkbait's Favorite Crackers",
                    name = "Harlan Sweete",
                    itemId = 159842,
                    spellId = 254813,
                    icon = "inv_misc_food_wheat_02",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
            },
          },
          {
            title = "Walk to Zuldazar",
            steps = {
              {
                title = "Run King's Rest (Dungeon)",
                type = "WeeklyDungeon",
                bosses = {
                  {
                    ID = 1040,
                    mount = "Mummified Raptor Skull",
                    name = "Dazar, The First King",
                    itemId = 159921,
                    spellId = 266058,
                    icon = "inv_armoredraptorundead",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
            },
          },
          {
            title = "Walk to Nazmir",
            steps = {
              {
                title = "Run The Underrot (Dungeon)",
                type = "WeeklyDungeon",
                bosses = {
                  {
                    ID = 1053,
                    mount = "Underrot Crawg Harness",
                    name = "Unbound Abomination",
                    itemId = 160829,
                    spellId = 273541,
                    icon = "inv_archaeology_ogres_chimera_riding_harness",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
            },
          },
        },
      },
      {
        title = "and Portal to Zandalar / Kul'Tiras and take the Teleporter / Flight Path to Mechagon",
        capital = true,
        steps = {
          {
            title = "Run Mechagon: Junkyard (Dungeon)",
            type = "WeeklyDungeon",
            bosses = {
              {
                ID = 1252,
                mount = "Mechagon Peacekeeper",
                name = "HK-8 Aerial Oppression Unit",
                itemId = 168826,
                spellId = 299158,
                icon = "inv_mechagonspidertank_brass",
                epic = true,
                note = "Mythic only",
              },
              {
                ID = 1227,
                mount = "Aerial Unit R-21/X",
                name = "King Mechagon",
                itemId = 168830,
                spellId = 290718,
                icon = "inv_hunterkillershipyellow",
                epic = true,
                note = "Hardmode only",
              },
            },
          },
        },
      },
      {
        title = "and Portal to Uldum",
        capital = true,
        steps = {
          {
            title = "Run Ny'alotha the Waking City (Raid)",
            type = "Raid",
            bosses = {
              {
                ID = 1293,
                mount = "Ny'alotha Allseer",
                name = "N'zoth the Corruptor",
                itemId = 174872,
                spellId = 308814,
                icon = "inv_eyeballjellyfishmount",
                epic = true,
                note = "Mythic only",
              },
            },
          },
        },
      },
      {
        title = "and Portal to Oribos",
        notes = "Set Hearthstone to Faction Capital",
        capital = true,
        steps = {
          {
            title = "Flightpath to Bastion",
            steps = {
              {
                title = "Run Necrotic Wake (Dungeon)",
                type = "WeeklyDungeon",
                bosses = {
                  {
                    ID = 1406,
                    mount = "Marrowfang",
                    name = "Nalthor the Rimebinder",
                    itemId = 181819,
                    spellId = 336036,
                    icon = "inv_maldraxxusflyermount_red",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
            },
          },
          {
            title = "Fly to Tazavesh",
            steps = {
              {
                title = "Run Tazavesh the Veiled Market (Dungeon)",
                type = "Dungeon",
                bosses = {
                  {
                    ID = 1481,
                    mount = "Cartel Master's Gearglider",
                    name = "So'leah",
                    itemId = 186638,
                    spellId = 353263,
                    icon = "inv_brokermount_dark",
                    epic = true,
                    note = "Heroic (Repeatable)/Mythic",
                  },
                },
              },
            },
          },
          {
            title = "Fly to Oribos, then Portal to The Maw",
            steps = {
              {
                title = "Run Sanctum of Domination (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 1500,
                    mount = "Sanctum Gloomcharger",
                    name = "The Nine",
                    itemId = 186656,
                    spellId = 354351,
                    icon = "ability_mount_mawhorsespikes_purple",
                    epic = true,
                    note = "LFR/Normal/Heroic/Mythic",
                  },
                  {
                    ID = 1471,
                    mount = "Vengeance",
                    name = "Lady Sylvanas Windrunner",
                    itemId = 186642,
                    spellId = 351195,
                    icon = "inv_dragonhawkmountshadowlands",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
            },
          },
          {
            title = "Teleport to Zereth Mortis",
            steps = {
              {
                title = "Run Sepulcher of the First Ones (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 1587,
                    mount = "Zereth Overseer",
                    name = "The Jailer",
                    itemId = 190768,
                    spellId = 368158,
                    icon = "inv_progenitorbotminemount",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
            },
          },
        },
      },
      {
        title = "and Portal to Valdrakken",
        notes = "Set Hearthstone to Faction Capital",
        capital = true,
        steps = {
          {
            title = "Flightpath to Dawn of the Infinites",
            steps = {
              {
                title = "Run Dawn of the Infinites (Dungeon)",
                type = "Raid",
                bosses = {
                  {
                    ID = 69,
                    mount = "Deathcharger's Reins",
                    name = "Chrono-Lord Deios",
                    itemId = 13335,
                    spellId = 17481,
                    icon = "ability_mount_undeadhorse",
                    epic = true,
                    note = "Mythic only - from Quantum Courser item",
                  },
                  {
                    ID = 185,
                    mount = "Raven Lord",
                    name = "Chrono-Lord Deios",
                    itemId = 32768,
                    spellId = 41252,
                    icon = "inv-mount_raven_54",
                    epic = true,
                    note = "Mythic only - from Quantum Courser item",
                  },
                  {
                    ID = 213,
                    mount = "Swift White Hawkstrider",
                    name = "Chrono-Lord Deios",
                    itemId = 35513,
                    spellId = 46628,
                    icon = "ability_mount_cockatricemountelite_white",
                    epic = true,
                    note = "Mythic only - from Quantum Courser item",
                  },
                  {
                    ID = 264,
                    mount = "Blue Proto-Drake",
                    name = "Chrono-Lord Deios",
                    itemId = 44151,
                    spellId = 59996,
                    icon = "ability_mount_drake_proto",
                    epic = true,
                    note = "Mythic only - from Quantum Courser item",
                  },
                  {
                    ID = 395,
                    mount = "Drake of the North Wind",
                    name = "Chrono-Lord Deios",
                    itemId = 63040,
                    spellId = 88742,
                    icon = "inv_misc_stormdragonpale",
                    epic = true,
                    note = "Mythic only - from Quantum Courser item",
                  },
                  {
                    ID = 397,
                    mount = "Vitreous Stone Drake",
                    name = "Chrono-Lord Deios",
                    itemId = 63043,
                    spellId = 88746,
                    icon = "inv_misc_stonedragonblue",
                    epic = true,
                    note = "Mythic only - from Quantum Courser item",
                  },
                  {
                    ID = 410,
                    mount = "Armored Razzashi Raptor",
                    name = "Chrono-Lord Deios",
                    itemId = 68823,
                    spellId = 96491,
                    icon = "ability_mount_raptor",
                    epic = true,
                    note = "Mythic only - from Quantum Courser item",
                  },
                  {
                    ID = 411,
                    mount = "Swift Zulian Panther",
                    name = "Chrono-Lord Deios",
                    itemId = 68824,
                    spellId = 96499,
                    icon = "ability_mount_blackpanther",
                    epic = true,
                    note = "Mythic only - from Quantum Courser item",
                  },
                  {
                    ID = 781,
                    mount = "Infinite Timereaver",
                    name = "Chrono-Lord Deios",
                    itemId = 133543,
                    spellId = 201098,
                    icon = "inv_infinitedragonmount",
                    epic = true,
                    note = "Mythic only - from Quantum Courser item",
                  },
                  {
                    ID = 875,
                    mount = "Midnight's Eternal Reins",
                    name = "Chrono-Lord Deios",
                    itemId = 142236,
                    spellId = 229499,
                    icon = "inv_skeletalwarhorse_black",
                    epic = true,
                    note = "Mythic only - from Quantum Courser item",
                  },
                  {
                    ID = 995,
                    mount = "Sharkbait's Favorite Crackers",
                    name = "Chrono-Lord Deios",
                    itemId = 159842,
                    spellId = 254813,
                    icon = "inv_misc_food_wheat_02",
                    epic = true,
                    note = "Mythic only - from Quantum Courser item",
                  },
                  {
                    ID = 1040,
                    mount = "Mummified Raptor Skull",
                    name = "Chrono-Lord Deios",
                    itemId = 159921,
                    spellId = 266058,
                    icon = "inv_armoredraptorundead",
                    epic = true,
                    note = "Mythic only - from Quantum Courser item",
                  },
                  {
                    ID = 1053,
                    mount = "Underrot Crawg Harness",
                    name = "Chrono-Lord Deios",
                    itemId = 160829,
                    spellId = 273541,
                    icon = "inv_archaeology_ogres_chimera_riding_harness",
                    epic = true,
                    note = "Mythic only - from Quantum Courser item",
                  },
                  {
                    ID = 1252,
                    mount = "Mechagon Peacekeeper",
                    name = "Chrono-Lord Deios",
                    itemId = 168826,
                    spellId = 299158,
                    icon = "inv_mechagonspidertank_brass",
                    epic = true,
                    note = "Mythic only - from Quantum Courser item",
                  },
                  {
                    ID = 1406,
                    mount = "Marrowfang",
                    name = "Chrono-Lord Deios",
                    itemId = 181819,
                    spellId = 336036,
                    icon = "inv_maldraxxusflyermount_red",
                    epic = true,
                    note = "Mythic only - from Quantum Courser item",
                  },
                  {
                    ID = 1481,
                    mount = "Cartel Master's Gearglider",
                    name = "Chrono-Lord Deios",
                    itemId = 186638,
                    spellId = 353263,
                    icon = "inv_brokermount_dark",
                    epic = true,
                    note = "Mythic only - from Quantum Courser item",
                  },
                },
              },
            },
          },
          {
            title = "Take the portal to the Emerald Dream in the Emerald Enclave",
            steps = {
              {
                title = "Run Amirdrassil, the Dream's Hope (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 1818,
                    mount = "Anu'relos, Flame's Guidance",
                    name = "Fyrakk",
                    itemId = 210061,
                    spellId = 424484,
                    icon = "inv_dreamowl_firemount",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
            },
          },
        },
      },
      {
        title = "and Portal to Dornogal",
        notes = "Set Hearthstone to Faction Capital",
        capital = true,
        steps = {
          {
            title = "Flightpath to The Ringing Deeps",
            steps = {
              {
                title = "Run The Stonevault (Dungeon)",
                type = "WeeklyDungeon",
                bosses = {
                  {
                    ID = 2119,
                    mount = "Stonevault Mechsuit",
                    name = "Void Speaker Eirich",
                    itemId = 221765,
                    spellId = 442358,
                    icon = "inv_dwarvenmechboss",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
            },
          },
          {
            title = "Flightpath to Ringing Deeps",
            steps = {
              {
                title = "Run Darkflame Cleft (Dungeon)",
                type = "WeeklyDungeon",
                bosses = {
                  {
                    ID = 2204,
                    mount = "Wick",
                    name = "The Darkness",
                    itemId = 225548,
                    spellId = 449264,
                    icon = "inv_molemount_brown",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
            },
          },
          {
            title = "Flightpath to Azj'Kahet",
            steps = {
              {
                title = "Run Nerub-ar Palace (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 2219,
                    mount = "Sureki Skyrazor",
                    name = "Queen Ansurek",
                    itemId = 224147,
                    spellId = 451486,
                    icon = "inv_nerubianwarbeastmount_blue",
                    epic = true,
                    note = "LFR/Normal/Heroic/Mythic",
                  },
                  {
                    ID = 2223,
                    mount = "Ascendant Skyrazor",
                    name = "Queen Ansurek",
                    itemId = 224151,
                    spellId = 451491,
                    icon = "inv_nerubianwarbeastmount_white",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
            },
          },
          {
            title = "and Portal to Dornogal and then take the teleporter to Undermine",
            capital = true,
            steps = {
              {
                title = "Run Liberation of Undermine (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 2507,
                    mount = "Prototype A.S.M.R.",
                    name = "Chrome King Gallywix",
                    itemId = 236960,
                    spellId = 1221155,
                    icon = "inv_goblinflyingmachine",
                    epic = true,
                    note = "LFR/Normal/Heroic/Mythic",
                  },
                  {
                    ID = 2487,
                    mount = "The Big G",
                    name = "Chrome King Gallywix",
                    itemId = 235626,
                    spellId = 235626,
                    icon = "inv_gallywixmechmount",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
            },
          },
          {
            title = "and Portal to Dornogal and then take the teleporter to K'aresh",
            capital = true,
            steps = {
              {
                title = "Run Manaforge Omega (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 2569,
                    mount = "Unbound Star-Eater",
                    name = "Dimensius",
                    itemId = 243061,
                    spellId = 1234573,
                    icon = "inv_cosmicdragonmount",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
            },
          },
        },
      },
      {
        title = "and Portal to Silvermoon",
        notes = "Set Hearthstone to Faction Capital",
        capital = true,
        steps = {
          {
            title = "Flightpath to Isle of Quel'Danas",
            steps = {
              {
                title = "Run Magister's Terrace (Midnight Dungeon)",
                type = "Dungeon",
                bosses = {
                  {
                    ID = 2817,
                    mount = "Lucent Hawkstrider",
                    name = "Degentrius",
                    itemId = 260231,
                    spellId = 1265784,
                    icon = "inv_hawkstridermount_white",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
              {
                title = "Run March on Quel'Danas (Raid)",
                type = "Raid",
                bosses = {
                  {
                    ID = 2607,
                    mount = "Ashes of Belo'ren",
                    name = "Midnight Falls",
                    itemId = 246590,
                    spellId = 1242904,
                    icon = "inv_darkwellphoenixmount",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
            },
          },
          {
            title = "Flightpath to Eversong Woods",
            steps = {
              {
                title = "Run Windrunner Spire (Dungeon)",
                type = "Dungeon",
                bosses = {
                  {
                    ID = 2805,
                    mount = "Spectral Hawkstrider",
                    name = "The Restless Heart",
                    itemId = 262914,
                    spellId = 1263635,
                    icon = "inv_white_hawkstrider",
                    epic = true,
                    note = "Mythic only",
                  },
                },
              },
            },
          },
        },
      },
    },
  },
}
