-- GENERATED by scripts/build-mounts.mjs — DO NOT EDIT BY HAND.
-- World "drop" mounts not tied to an instance boss (rares, treasures, world quests…).

EasyMountFarmerWorld = { {
  category = "worldrare",
  mountID = 1378,
  mount = "Aile de l’effroi du moissonneur",
  source = "Butin : Trésor de guerre du moissonneur / Région : L’Antre",
}, {
  category = "worldrare",
  mountID = 1310,
  mount = "Aile de l’effroi horrible",
  source = "Butin : Harika l’Horrible / Congrégation : Venthyrs / Région : Revendreth",
}, {
  category = "worldrare",
  mountID = 1732,
  mount = "Aile-de-schiste de cobalt",
  source = "Butin : Karokta / Région : grotte de Zaralek",
}, {
  category = "worldrare",
  mountID = 944,
  mount = "Aile-tempête valarjar",
  source = "Butin : Coffre renforcé valarjar /",
}, {
  category = "worldrare",
  mountID = 1778,
  mount = "Albatros à palmes dorées",
  source = "Butin : failles temporelles / Vendeuse : Sorotis / Zone : réservoir du Bastion de Tyr / Prix : 3 000|Hcurrency:2594|h|h",
}, {
  category = "worldrare",
  mountID = 2176,
  mount = "Alunira",
  source = "Butin : Alunira / Région : île de Dorn",
}, {
  category = "worldrare",
  mountID = 2561,
  mount = "Ardospine curieuse",
  source = "Butin : cache du sommet frétillante / Région : K’aresh",
}, {
  category = "worldrare",
  mountID = 1183,
  mount = "Arrache-Crâne",
  source = "Butin : Arrache-Crâne / Région : Hautes-terres Arathies",
}, {
  category = "worldrare",
  mountID = 1434,
  mount = "Aurélidé stellaire des profondeurs",
  source = "Butin : Hirukon / Région : Zereth Mortis",
}, {
  category = "worldrare",
  mountID = 202,
  mount = "Bélier rapide de la fête des Brasseurs",
  source = "Butin : Coffre au trésor en forme de tonneau / Fête : Fête des Brasseurs",
}, {
  category = "worldrare",
  mountID = 2295,
  mount = "Bombardier de Baille-Fonds",
  source = "Butin : trésor de Baille-Fonds / Région : Terremine",
}, {
  category = "worldrare",
  mountID = 2640,
  mount = "Bombardier des Brasseurs",
  source = "Butin : Coren Navrebière / Évènement saisonnier : fête des Brasseurs",
}, {
  category = "worldrare",
  mountID = 1176,
  mount = "Bondisseur rochecorne",
  source = "Butin : Exploration des îles /",
}, {
  category = "worldrare",
  mountID = 1319,
  mount = "Bourdon malveillant",
  source = "Butin : Mange-cadavres / Région : Uldum",
}, {
  category = "worldrare",
  mountID = 352,
  mount = "Brise-cœur X-45",
  source = "Butin : Boîte en forme de cœur / Évènement : De l’amour dans l’air",
}, {
  category = "worldrare",
  mountID = 616,
  mount = "Brocheperle sombrepoil",
  source = "Butin : Trésor oublié de l’envahisseur",
}, {
  category = "worldrare",
  mountID = 993,
  mount = "Caquet",
  source = "Butin : Exploration des îles /",
}, {
  category = "worldrare",
  mountID = 961,
  mount = "Cauchemar lucide",
  source = "Butin : Vœu du mystère",
}, {
  category = "worldrare",
  mountID = 2615,
  mount = "Chagrynx traqueracine",
  source = "Butin : créatures rares d’Harandar /",
}, {
  category = "worldrare",
  mountID = 122,
  mount = "Char d’assaut qiraji noir",
  source = "Butin : Butin mondial / Lieu : Temple d’Ahn’Qiraj",
}, {
  category = "worldrare",
  mountID = 1304,
  mount = "Chasseur d’âmes antrelige",
  source = "Butin : Molosse d’ombre rassasié / Région : L’Antre",
}, {
  category = "worldrare",
  mountID = 1211,
  mount = "Chasseuse gorgée de sang",
  source = "Butin : Exploration des îles",
}, {
  category = "worldrare",
  mountID = 1437,
  mount = "Chien de guerre lié par le combat",
  source = "Butin : Théâtre de la Souffrance / Région : Maldraxxus",
}, {
  category = "worldrare",
  mountID = 1781,
  mount = "Chien de soufre",
  source = "Butin : failles temporelles / Vendeuse : approvisionneuse Qorra / Zone : réservoir du Bastion de Tyr / Prix : 3 000|Hcurrency:2594|h|h",
}, {
  category = "worldrare",
  mountID = 1200,
  mount = "Chimère d’Orneval",
  source = "Butin : Alash’anir / Région : Sombrivage /",
}, {
  category = "worldrare",
  mountID = 1025,
  mount = "Conscience collective",
  source = "Butin : Conscience collective /",
}, {
  category = "worldrare",
  mountID = 942,
  mount = "Courserêve sauvage",
  source = "Butin : Cache tisse-rêves",
}, {
  category = "worldrare",
  mountID = 2499,
  mount = "Coursier du vent marqué par le Vide",
  source = "Butin : coursier du vent marqué par le Vide / Région : vision d’Orgrimmar (redécouverte) /",
}, {
  category = "worldrare",
  mountID = 1297,
  mount = "Couvée de Ha Li",
  source = "Butin : Ha-Li / Région : Val de l’Éternel printemps",
}, {
  category = "worldrare",
  mountID = 980,
  mount = "Crache-acide",
  source = "Butin : Skreeg le Dévoreur / Région : Érédath",
}, {
  category = "worldrare",
  mountID = 838,
  mount = "Créature des grands fonds",
  source = "Butin : Kosumoth l’Affamé",
}, {
  category = "worldrare",
  mountID = 1455,
  mount = "Cuirasaure de béryl",
  source = "Butin : Fournitures de l’Avancée de la mort / Région : Korthia",
}, {
  category = "worldrare",
  mountID = 1506,
  mount = "Cuirasaure écarlate",
  source = "Butin : Malbog / Région : Korthia",
}, {
  category = "worldrare",
  mountID = 2288,
  mount = "D.E.B.R.I.S.eur gobelin personnalisé",
  source = "Butin : tas de débris triés / Région : Terremine",
}, {
  category = "worldrare",
  mountID = 1307,
  mount = "Danse-Soleil",
  source = "Butin : Danse-Soleil / Région : Le Bastion /",
}, {
  category = "worldrare",
  mountID = 2334,
  mount = "Déchiqueteur de vagues gobelin en bronze",
  source = "Butin : trésor imprégné de ténèbres / Région : Terremine",
}, {
  category = "worldrare",
  mountID = 2303,
  mount = "Déchiqueteur gobelin pourpre",
  source = "Butin : Service d’expédition / Région : Terremine",
}, {
  category = "worldrare",
  mountID = 1372,
  mount = "Défenses-de-sang cloquéchine",
  source = "Butin : Porteguerre Mal’korak / Région : Maldraxxus",
}, {
  category = "worldrare",
  mountID = 2767,
  mount = "Défenseur de Fulgarion maîtrisé",
  source = "Butin : cache de victoire de Fulgarion / Région : tempête du Vide",
}, {
  category = "worldrare",
  mountID = 1248,
  mount = "Dériveur de la Décharge",
  source = "Butin : Rouille-Plume / Région : Mécagone",
}, {
  category = "worldrare",
  mountID = 2603,
  mount = "Dernier déjeuner de Sthaarbs",
  source = "Butin : Sthaarbs / Région : K’aresh",
}, {
  category = "worldrare",
  mountID = 2605,
  mount = "Destrier d’Inarius",
  source = "Butin : Émissaires cupides",
}, {
  category = "worldrare",
  mountID = 1502,
  mount = "Destrier déchu",
  source = "Butin : Destrier déchu / Région : L’Antre",
}, {
  category = "worldrare",
  mountID = 931,
  mount = "Destrier du courroux maudit de seigneur du Néant",
  source = "Butin : Seigneur Hel’nurath / Région : Rivage Brisé",
}, {
  category = "worldrare",
  mountID = 2623,
  mount = "Destrier macabre du Cavalier sans tête",
  source = "Butin : Citrouille remplie de butin / Fête : Sanssaint /",
}, {
  category = "worldrare",
  mountID = 1501,
  mount = "Destrier sinistre lié",
  source = "Butin : Mystérieux cadeau de Ve’nari / Région : L’Antre",
}, {
  category = "worldrare",
  mountID = 1619,
  mount = "Dracamandre antique",
  source = "Butin : confins Interdits /",
}, {
  category = "worldrare",
  mountID = 1779,
  mount = "Dragon gangrorage",
  source = "Butin : failles temporelles / Vendeuse : Falara Chantenuit / Zone : réservoir du Bastion de Tyr / Prix : 3 000|Hcurrency:2594|h|h",
}, {
  category = "worldrare",
  mountID = 248,
  mount = "Drake bronze",
  source = "Butin : Corrupteur infini / Région : Épuration de Stratholme",
}, {
  category = "worldrare",
  mountID = 393,
  mount = "Drake de pierre phosphorescent",
  source = "Butin : Aeonaxx / Lieu : Tréfonds /",
}, {
  category = "worldrare",
  mountID = 1314,
  mount = "Drake des quatre vents",
  source = "Butin : Ishak des Quatre vents / Région : Uldum",
}, {
  category = "worldrare",
  mountID = 1212,
  mount = "Écailles-de-tonnerre insulaire",
  source = "Butin : Exploration des îles",
}, {
  category = "worldrare",
  mountID = 2749,
  mount = "Écho d’Aln’sharan",
  source = "Butin : Aln’sharan / Région : Harandar",
}, {
  category = "worldrare",
  mountID = 2192,
  mount = "Engeance de Beledar",
  source = "Butin : Engeance de Beledar / Région : Sainte-Chute",
}, {
  category = "worldrare",
  mountID = 2497,
  mount = "Étalon forgé par le Vide",
  source = "Butin : étalon forgé par le Vide / Région : vision de Hurlevent (redécouverte)",
}, {
  category = "worldrare",
  mountID = 612,
  mount = "Étalon sabot-de-sang",
  source = "Butin : Nakk le Foudroyeur / Lieu : Nagrand",
}, {
  category = "worldrare",
  mountID = 1350,
  mount = "Fauche-griffe colossal",
  source = "Butin : Fournitures de l’Armée immortelle / Région : Maldraxxus",
}, {
  category = "worldrare",
  mountID = 293,
  mount = "Faucon du destin illidari",
  source = "Butin : Marche-funeste / Région : Tanaris",
}, {
  category = "worldrare",
  mountID = 2758,
  mount = "Faucon-dragon cobalt",
  source = "Butin : créatures rares du bois des Chants éternels /",
}, {
  category = "worldrare",
  mountID = 2762,
  mount = "Faucon-pérégrin céruléen",
  source = "Butin : créatures rares du bois des Chants éternels /",
}, {
  category = "worldrare",
  mountID = 1327,
  mount = "Fidèle quilen de Ren",
  source = "Butin : Grand-veneur Ren / Région : Val de l’Éternel printemps",
}, {
  category = "worldrare",
  mountID = 2708,
  mount = "Folibri éclatant",
  source = "Butin : créatures rares d’Harandar /",
}, {
  category = "worldrare",
  mountID = 970,
  mount = "Foule-chaos affolé",
  source = "Butin : Kravos le Dompteur / Région : Érédath",
}, {
  category = "worldrare",
  mountID = 614,
  mount = "Foule-prairie tacheté",
  source = "Butin : Luk’hok / Région : Nagrand",
}, {
  category = "worldrare",
  mountID = 2274,
  mount = "Frappeur des Flots noirs",
  source = "Butin : trésor des Flots noirs / Région : Terremine",
}, {
  category = "worldrare",
  mountID = 984,
  mount = "Gangrebroyeur béni",
  source = "Butin : Cantine resplendissante",
}, {
  category = "worldrare",
  mountID = 983,
  mount = "Gangrebroyeur glorieux",
  source = "Butin : Cantine resplendissante",
}, {
  category = "worldrare",
  mountID = 985,
  mount = "Gangrebroyeur vengeur",
  source = "Butin : Cantine resplendissante",
}, {
  category = "worldrare",
  mountID = 642,
  mount = "Garn gueule-d’acier",
  source = "Butin : Trésor oublié de l’envahisseur",
}, {
  category = "worldrare",
  mountID = 657,
  mount = "Garn nocthurle",
  source = "Butin : Nok-Karosh / Lieu : Crête de Givrefeu",
}, {
  category = "worldrare",
  mountID = 1627,
  mount = "Gastéromentaire baveux",
  source = "Butin : confins Interdits /",
}, {
  category = "worldrare",
  mountID = 1798,
  mount = "Glacemonde azur",
  source = "Butin : Marche-funeste / Région : Tanaris",
}, {
  category = "worldrare",
  mountID = 2950,
  mount = "Glissespore lumineux",
  source = "Butin : Embourbe-pourri / Région : Chute-des-Spores",
}, {
  category = "worldrare",
  mountID = 1415,
  mount = "Gobeur arboricole",
  source = "Butin : Gargan’tuzz / Région : Sylvarden",
}, {
  category = "worldrare",
  mountID = 2602,
  mount = "Goinfre transposé",
  source = "Butin : essaims de dévoreurs / Région : Tazavesh /",
}, {
  category = "worldrare",
  mountID = 627,
  mount = "Grand grisebroche",
  source = "Butin : Gorok / Région : Crête de Givrefeu /",
}, {
  category = "worldrare",
  mountID = 226,
  mount = "Grand kodo de la fête des Brasseurs",
  source = "Butin : Coffre au trésor en forme de tonneau / Fête : Fête des Brasseurs",
}, {
  category = "worldrare",
  mountID = 287,
  mount = "Grand mammouth de guerre noir",
  source = "Butin : Butin de boss / Lieu : Caveau d’Archavon",
}, {
  category = "worldrare",
  mountID = 2496,
  mount = "Griffon marqué par le Vide",
  source = "Butin : griffon marqué par le Vide / Région : vision de Hurlevent (redécouverte) / /",
}, {
  category = "worldrare",
  mountID = 981,
  mount = "Grince-dents caustique",
  source = "Butin : Argus",
}, {
  category = "worldrare",
  mountID = 626,
  mount = "Groin-froid géant",
  source = "Butin : Trésor oublié de l’envahisseur",
}, {
  category = "worldrare",
  mountID = 655,
  mount = "Gronnlin peau-solaire",
  source = "Butin : Martèlepoing / Région : Gorgrond",
}, {
  category = "worldrare",
  mountID = 2281,
  mount = "Grossiste de Gentepression",
  source = "Butin : trésor de Gentepression / Région : Terremine",
}, {
  category = "worldrare",
  mountID = 979,
  mount = "Gueule-écumante cramoisie",
  source = "Butin : Gueule putride / Région : Étendues Antoréennes",
}, {
  category = "worldrare",
  mountID = 420,
  mount = "Hippocampe assujetti",
  source = "Butin : Poséidus / Région : Vashj’ir",
}, {
  category = "worldrare",
  mountID = 943,
  mount = "Hippogriffe nuelle",
  source = "Butin : Coffre de Farondis /",
}, {
  category = "worldrare",
  mountID = 1672,
  mount = "Jeune zenet",
  source = "Butin : œuf de zenet / Région : plaines d’Ohn’ahra",
}, {
  category = "worldrare",
  mountID = 1213,
  mount = "Jument ressuscitée",
  source = "Butin : Exploration des îles /",
}, {
  category = "worldrare",
  mountID = 1201,
  mount = "Kodo effrayé",
  source = "Butin : Kodo effrayé / Région : Sombrivage /",
}, {
  category = "worldrare",
  mountID = 2289,
  mount = "Koordinatrice Kapitale",
  source = "Butin : trésor de la KapitalRisk / Région : Terremine",
}, {
  category = "worldrare",
  mountID = 2601,
  mount = "Krolusk perlescent",
  source = "Butin : Urmag / Région : K’aresh",
}, {
  category = "worldrare",
  mountID = 649,
  mount = "Loup redoutable anthracite",
  source = "Butin : Trésor oublié de l’envahisseur",
}, {
  category = "worldrare",
  mountID = 2194,
  mount = "Lynx impérial audacieux",
  source = "Butin : Propager la lumière / Région : Sainte-Chute",
}, {
  category = "worldrare",
  mountID = 2535,
  mount = "Lynx marqué par le Vide",
  source = "Butin :sac de sectatrice confisqué",
}, {
  category = "worldrare",
  mountID = 1315,
  mount = "Mâche-Courrier",
  source = "Butin : Mâche-Courrier / Région : Visions horrifiques",
}, {
  category = "worldrare",
  mountID = 1362,
  mount = "Mâche-prairie gueule-épine",
  source = "Butin : Dompteur de gorms Tizo / Région : Sylvarden",
}, {
  category = "worldrare",
  mountID = 2291,
  mount = "Machine volante recyclée de Gobelin milliardaire",
  source = "Butin : détritus du Gallagio / Région : Terremine",
}, {
  category = "worldrare",
  mountID = 1645,
  mount = "Magmammouth reconstitué",
  source = "Butin : poussées oniriques",
}, {
  category = "worldrare",
  mountID = 1475,
  mount = "Main de Bahmethra",
  source = "Butin : Tourmenteurs de Tourment / Région : L’Antre /",
}, {
  category = "worldrare",
  mountID = 1634,
  mount = "Mammouth moussu",
  source = "Butin : caveaux de Zskera /",
}, {
  category = "worldrare",
  mountID = 1317,
  mount = "Maraudeur du désert",
  source = "Butin : Croque-Charogne / Région : Uldum",
}, {
  category = "worldrare",
  mountID = 1454,
  mount = "Marteleur apprivoisé",
  source = "Butin : Fournitures du Codex des archivistes / Région : Korthia /",
}, {
  category = "worldrare",
  mountID = 1782,
  mount = "Mastodonte perfectionné",
  source = "Butin : failles temporelles / Vendeuse : Flora la Foreuse / Zone : réservoir du Bastion de Tyr / Prix : 3 000|Hcurrency:2594|h|h",
}, {
  category = "worldrare",
  mountID = 1229,
  mount = "Mécaraignée rouillée",
  source = "Butin : Mécagone /",
}, {
  category = "worldrare",
  mountID = 1169,
  mount = "Méduse des vagues",
  source = "Butin : Exploration des îles /",
}, {
  category = "worldrare",
  mountID = 2498,
  mount = "Mère de meute marquée par le Vide",
  source = "Butin : mère de meute marquée par le Vide / Région : vision d’Orgrimmar (redécouverte)",
}, {
  category = "worldrare",
  mountID = 1178,
  mount = "Molosse éternel de Qinsho",
  source = "Butin : Exploration des îles /",
}, {
  category = "worldrare",
  mountID = 219,
  mount = "Monture du Cavalier sans tête",
  source = "Butin : Citrouille remplie de butin / Fête : Sanssaint /",
}, {
  category = "worldrare",
  mountID = 1237,
  mount = "Mordragon royal",
  source = "Butin : Fournitures ankoïennes / Butin : Fournitures des Affranchis",
}, {
  category = "worldrare",
  mountID = 643,
  mount = "Morne-croc chanteguerre",
  source = "Butin : Vengeance, Serres-mort, Poing-de-terreur, Compresseur funeste / Région : Jungle de Tanaan /",
}, {
  category = "worldrare",
  mountID = 1174,
  mount = "Mustang des hautes-terres",
  source = "Butin : Chevauche-malheur Sombrenfer / Région : Hautes-terres Arathies",
}, {
  category = "worldrare",
  mountID = 1173,
  mount = "Mustang des hautes-terres dressé",
  source = "Butin : Chevalier-capitaine Aldrin / Région : Hautes-terres Arathies",
}, {
  category = "worldrare",
  mountID = 1514,
  mount = "Mutilateur enragé",
  source = "Butin : Konthrogz l’Oblitérateur / Région : Korthia",
}, {
  category = "worldrare",
  mountID = 535,
  mount = "Navrecorne primordial ardoise",
  source = "Butin : Porteguerre zandalari / Région : Terres de l’Angoisse, étendues sauvages de Krasarang, sommet de Kun-Lai, steppes de Tanglong, vallée des Quatre vents",
}, {
  category = "worldrare",
  mountID = 534,
  mount = "Navrecorne primordial d’ambre",
  source = "Butin : Porteguerre zandalari / Région : Terres de l’Angoisse, sommet de Kun-Lai, steppes de Tanglong, vallée des Quatre vents",
}, {
  category = "worldrare",
  mountID = 536,
  mount = "Navrecorne primordial jade",
  source = "Butin : Porteguerre zandalari / Région : Terres de l’Angoisse, sommet de Kun-Lai, steppes de Tanglong, vallée des Quatre vents",
}, {
  category = "worldrare",
  mountID = 1438,
  mount = "Nécroraie bulbeuse",
  source = "Butin : Œuf de nécroraie suintant /",
}, {
  category = "worldrare",
  mountID = 1439,
  mount = "Nécroraie infestée",
  source = "Butin : Œuf de nécroraie suintant /",
}, {
  category = "worldrare",
  mountID = 1440,
  mount = "Nécroraie pestilentielle",
  source = "Butin : Œuf de nécroraie suintant /",
}, {
  category = "worldrare",
  mountID = 941,
  mount = "Noble-bois de Haut-Roc",
  source = "Butin : Fournitures de Haut-Roc /",
}, {
  category = "worldrare",
  mountID = 1209,
  mount = "Noble-bois peau-roche",
  source = "Butin : Exploration des îles",
}, {
  category = "worldrare",
  mountID = 1257,
  mount = "Onduleuse silencieuse",
  source = "Butin : Le grand Silence / Région : Nazjatar",
}, {
  category = "worldrare",
  mountID = 419,
  mount = "Ours de bataille amani",
  source = "Butin : Sac de Kasha",
}, {
  category = "worldrare",
  mountID = 237,
  mount = "Ours polaire blanc",
  source = "Butin : Butin hyldnir / Lieu : Pics Foudroyés",
}, {
  category = "worldrare",
  mountID = 1182,
  mount = "P’tit âne",
  source = "Butin : Surveillant Krix / Région : Hautes-terres Arathies",
}, {
  category = "worldrare",
  mountID = 2775,
  mount = "Pango fanécorce",
  source = "Butin : créatures rares de Zul’Aman /",
}, {
  category = "worldrare",
  mountID = 1199,
  mount = "Patte-Noire",
  source = "Butin : Agathe Wyrmebois / Région : Sombrivage / / Butin : Patte-Noire / Région : Sombrivage",
}, {
  category = "worldrare",
  mountID = 2764,
  mount = "Persécuteur brutobscure",
  source = "Butin : trésor du Duellum meurtrier / Région : perchoir des Maîtres",
}, {
  category = "worldrare",
  mountID = 2827,
  mount = "Persécuteur sanguin",
  source = "Butin : créatures rares de la tempête du Vide /",
}, {
  category = "worldrare",
  mountID = 1411,
  mount = "Pesteroc prédateur",
  source = "Butin : Gieger / Congrégation : Nécro-seigneurs / Région : Maldraxxus",
}, {
  category = "worldrare",
  mountID = 1428,
  mount = "Phalarden ambré",
  source = "Butin : Fournitures de l’Hallali / Région : Sylvarden /",
}, {
  category = "worldrare",
  mountID = 630,
  mount = "Potamodonte saphir",
  source = "Butin : Silthide / Région : Talador",
}, {
  category = "worldrare",
  mountID = 265,
  mount = "Proto-drake perdu dans le temps",
  source = "Butin : Proto-drake perdu dans le temps / Région : Pics Foudroyés",
}, {
  category = "worldrare",
  mountID = 278,
  mount = "Proto-drake vert",
  source = "Butin : Œuf brisé",
}, {
  category = "worldrare",
  mountID = 973,
  mount = "Raie de mana diaprée",
  source = "Butin : Ciaileron queue-venin / Région : Érédath",
}, {
  category = "worldrare",
  mountID = 974,
  mount = "Raie de mana éclatante",
  source = "Butin : Œuf taché par la corruption",
}, {
  category = "worldrare",
  mountID = 975,
  mount = "Raie de mana gangreluisante",
  source = "Butin : Œuf taché par la corruption",
}, {
  category = "worldrare",
  mountID = 976,
  mount = "Raie de mana scintillante",
  source = "Butin : Œuf taché par la corruption",
}, {
  category = "worldrare",
  mountID = 906,
  mount = "Raie de mana sombrespore",
  source = "Butin : Œuf taché par la corruption",
}, {
  category = "worldrare",
  mountID = 2751,
  mount = "Raie-tempête renforcée",
  source = "Butin : créatures rares de la tempête du Vide /",
}, {
  category = "worldrare",
  mountID = 1180,
  mount = "Raptor albinos véloce",
  source = "Butin : Chevaucheur de bêtes Kama / Région : Hautes-terres Arathies",
}, {
  category = "worldrare",
  mountID = 539,
  mount = "Raptor primordial noir",
  source = "Butin : Œuf primordial brisé",
}, {
  category = "worldrare",
  mountID = 538,
  mount = "Raptor primordial rouge",
  source = "Butin : Œuf primordial brisé",
}, {
  category = "worldrare",
  mountID = 540,
  mount = "Raptor primordial vert",
  source = "Butin : Œuf primordial brisé",
}, {
  category = "worldrare",
  mountID = 1508,
  mount = "Rasaile féroce",
  source = "Butin : Fournitures de l’Avancée de la mort / Région : Korthia",
}, {
  category = "worldrare",
  mountID = 1509,
  mount = "Rasaile grenat",
  source = "Butin : Réliwik le Provocateur / Région : Korthia",
}, {
  category = "worldrare",
  mountID = 1584,
  mount = "Rat de l’Antre crache-peste colossal",
  source = "Butin : Rhuv, Goinfre des ruines /",
}, {
  category = "worldrare",
  mountID = 1564,
  mount = "Rat de l’Antre lacère-âme colossal",
  source = "Butin : maître de la perfection (échelon 16) / Catégorie : Tourment /",
}, {
  category = "worldrare",
  mountID = 1565,
  mount = "Rat de l’Antre peau-ombreuse colossal",
  source = "Butin : Tourment, échelon 13 ou supérieur / Lieu : Tourment /",
}, {
  category = "worldrare",
  mountID = 1585,
  mount = "Rat de l’Antre spectre-lié colossal",
  source = "Butin : coffre de fournitures antreliges /",
}, {
  category = "worldrare",
  mountID = 1185,
  mount = "Redoutaile fanécorce",
  source = "Butin : Nimar le Pourfendeur / Région : Hautes-terres Arathies",
}, {
  category = "worldrare",
  mountID = 3036,
  mount = "Roc peint de la fête du Soleil",
  source = "Butin : Ahune / Évènement saisonnier : solstice d’été",
}, {
  category = "worldrare",
  mountID = 1410,
  mount = "Rocmort massif",
  source = "Butin : Erreur pourpre / Région : Maldraxxus",
}, {
  category = "worldrare",
  mountID = 1393,
  mount = "Rôdeur mantelume sauvage",
  source = "Butin : Valfir le Tenace / Congrégation : Faë nocturnes / Région : Sylvarden",
}, {
  category = "worldrare",
  mountID = 2205,
  mount = "Rufus la vieille taupe",
  source = "Butin : rôdeur des profondeurs / Zone : abîmes Retentissants",
}, {
  category = "worldrare",
  mountID = 1553,
  mount = "Rusarde libérée",
  source = "Butin : Croque-bise / Région : Travée d’Azur",
}, {
  category = "worldrare",
  mountID = 611,
  mount = "Sabot-glacé de la toundra",
  source = "Butin : Vengeance, Serres-mort, Poing-de-terreur, Compresseur funeste / Région : Jungle de Tanaan /",
}, {
  category = "worldrare",
  mountID = 1306,
  mount = "Sabot-sinistre rapide",
  source = "Butin : Jument nocturne / Région : Sylvarden",
}, {
  category = "worldrare",
  mountID = 1815,
  mount = "Sabre de rêve de la nuit hiémale",
  source = "Butin : réserve de graine onirique / Région : Rêve d’émeraude /",
}, {
  category = "worldrare",
  mountID = 1203,
  mount = "Sabre-de-nuit acajou",
  source = "Butin : Moxo le Tranche-Tête / Région : Sombrivage / / Butin : Athil Brûlerosée / Région : Sombrivage",
}, {
  category = "worldrare",
  mountID = 1205,
  mount = "Sabre-de-nuit kaldorei",
  source = "Butin : Croz Ragesang / Région : Sombrivage / / Butin : Ombregriffe / Région : Sombrivage",
}, {
  category = "worldrare",
  mountID = 1057,
  mount = "Serpent de sang de Nazjatar",
  source = "Butin : Adhérent des abysses / Région : Vallée Chantorage",
}, {
  category = "worldrare",
  mountID = 1445,
  mount = "Serpent visqueux",
  source = "Butin : Serpent visqueux / Région : Malepeste",
}, {
  category = "worldrare",
  mountID = 561,
  mount = "Serpent-nuage d’onyx fulminant",
  source = "Butin : Huolon / Lieu : Île du Temps figé",
}, {
  category = "worldrare",
  mountID = 517,
  mount = "Serpent-nuage de rubis fulminant",
  source = "Butin : Alani / Région : Val de l’Éternel printemps",
}, {
  category = "worldrare",
  mountID = 1311,
  mount = "Serpent-nuage ivoire",
  source = "Butin : Serpent-nuage ivoire / Région : Val de l’Éternel printemps",
}, {
  category = "worldrare",
  mountID = 682,
  mount = "Serre du Vide de l’Étoile noire",
  source = "Butin : Œuf de serre du Vide",
}, {
  category = "worldrare",
  mountID = 2760,
  mount = "Serre-tranchante amani",
  source = "Butin : créatures rares de Zul’Aman / /",
}, {
  category = "worldrare",
  mountID = 1477,
  mount = "Sombredogue immortel",
  source = "Butin : Trésor de guerre de l’Armée immortelle / Région : L’Antre",
}, {
  category = "worldrare",
  mountID = 2023,
  mount = "Tapis volant noble",
  source = "Butin : Daëtan Vifpanache / Évènement : Jardin des nobles",
}, {
  category = "worldrare",
  mountID = 905,
  mount = "Tapis volant tellurique",
  source = "Butin : Cache souffrenuit / /",
}, {
  category = "worldrare",
  mountID = 1366,
  mount = "Tauralus sabot-d’os",
  source = "Butin : Tahonta / Congrégation : Nécro-seigneurs / Région : Maldraxxus",
}, {
  category = "worldrare",
  mountID = 1370,
  mount = "Tauralus sabot-d’os cuirassé",
  source = "Butin : Sabrielle l’Ostéoclaste / Congrégation : Nécro-seigneurs / Région : Maldraxxus",
}, {
  category = "worldrare",
  mountID = 1476,
  mount = "Tranche-pattes de l’Hallali",
  source = "Butin : Trésor de guerre de l’Hallali / Région : L’Antre",
}, {
  category = "worldrare",
  mountID = 622,
  mount = "Tranchedos cuirassé",
  source = "Butin : Vengeance, Serres-mort, Poing-de-terreur, Compresseur funeste / Région : Jungle de Tanaan /",
}, {
  category = "worldrare",
  mountID = 1373,
  mount = "Tripépine",
  source = "Butin : Nerissa Sans-Cœur / Région : Maldraxxus",
}, {
  category = "worldrare",
  mountID = 2038,
  mount = "Trotte-bois argileux",
  source = "Butin : archives d’Azeroth",
}, {
  category = "worldrare",
  mountID = 636,
  mount = "Trotte-brise rapide",
  source = "Butin : Cours-les-Routes / Région : Vallée d’Ombrelune /",
}, {
  category = "worldrare",
  mountID = 1227,
  mount = "Unité aérienne R-21/X",
  source = "Butin : Roi Mécagone /",
}, {
  category = "worldrare",
  mountID = 1783,
  mount = "Vainqueur lié au Fléau",
  source = "Butin : failles temporelles / Vendeur : Baron Lesquille / Zone : réservoir du Bastion de Tyr / Prix : 3 000|Hcurrency:2594|h|h",
}, {
  category = "worldrare",
  mountID = 1175,
  mount = "Vengeur du Crépuscule",
  source = "Butin : Exploration des îles /",
}, {
  category = "worldrare",
  mountID = 947,
  mount = "Ver énigmatique de l’esprit",
  source = "Butin : Don des cherche-esprits",
}, {
  category = "worldrare",
  mountID = 955,
  mount = "Vil indomptable",
  source = "Butin : Dresseur de molosse Kerrax / Région : Étendues Antoréennes",
}, {
  category = "worldrare",
  mountID = 1379,
  mount = "Volant du marais des Affres",
  source = "Butin : Famu l’Infini / Région : Revendreth",
}, {
  category = "worldrare",
  mountID = 1328,
  mount = "Xinlao",
  source = "Butin : Anh De le Loyal / Région : Val de l’Éternel printemps",
} }
