#!/usr/bin/env node
// build-data.mjs — converts SimpleArmory's planner (data/planner.json) into Lua
// data consumed by the addon.
//
// Produces:
//   SAMounts/RouteData.lua          <- Lua table of the route tree (GENERATED, do not edit)
//   scripts/Locations.skeleton.lua      <- skeleton to fill by hand (coords/lockout/diff/encounters)
//   SAMounts/Locations.lua          <- created ONLY if it does not exist yet (never overwritten)
//
// Usage: node scripts/build-data.mjs

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SRC = join(ROOT, 'data', 'planner.json');
const OUT_ROUTE = join(ROOT, 'SAMounts', 'RouteData.lua');
const OUT_SKELETON = join(ROOT, 'scripts', 'Locations.skeleton.lua');
const OUT_LOCATIONS = join(ROOT, 'SAMounts', 'Locations.lua');

// --- read ------------------------------------------------------------------
const planner = JSON.parse(readFileSync(SRC, 'utf8'));
if (!Array.isArray(planner.steps)) {
  throw new Error('invalid planner.json: missing "steps"');
}

// --- Lua helpers -----------------------------------------------------------
const IDENT = /^[A-Za-z_][A-Za-z0-9_]*$/;

function luaString(s) {
  return '"' + String(s)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '') + '"';
}

function luaKey(k) {
  return IDENT.test(k) ? k : `[${luaString(k)}]`;
}

function luaValue(v, indent) {
  if (v === null || v === undefined) return 'nil';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'nil';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'string') return luaString(v);
  if (Array.isArray(v)) return luaArray(v, indent);
  if (typeof v === 'object') return luaTable(v, indent);
  return 'nil';
}

function luaArray(arr, indent) {
  if (arr.length === 0) return '{}';
  const inner = indent + '  ';
  const parts = arr.map((item) => inner + luaValue(item, inner));
  return '{\n' + parts.join(',\n') + ',\n' + indent + '}';
}

function luaTable(obj, indent) {
  const keys = Object.keys(obj);
  if (keys.length === 0) return '{}';
  const inner = indent + '  ';
  const parts = keys.map((k) => `${inner}${luaKey(k)} = ${luaValue(obj[k], inner)}`);
  return '{\n' + parts.join(',\n') + ',\n' + indent + '}';
}

// --- step normalization ----------------------------------------------------
// Keep only fields the addon needs, convert boss.ID (string) to a number, and
// preserve the nested structure (steps).
const STEP_FLAGS = ['capital', 'startStep', 'finalStep', 'hearth', 'unavailable', 'boosted'];

function normBoss(b) {
  const out = {};
  if (b.ID !== undefined) out.ID = Number(b.ID);          // mount journal ID
  if (b.mount !== undefined) out.mount = b.mount;
  if (b.name !== undefined) out.name = b.name;            // boss name
  if (b.itemId !== undefined) out.itemId = Number(b.itemId);
  if (b.spellId !== undefined) out.spellId = Number(b.spellId);
  if (b.icon !== undefined) out.icon = b.icon;
  if (b.epic !== undefined) out.epic = !!b.epic;
  if (b.note !== undefined) out.note = b.note;
  if (b.isAlliance) out.isAlliance = true;
  if (b.isHorde) out.isHorde = true;
  return out;
}

function normStep(s) {
  const out = {};
  if (s.title !== undefined) out.title = s.title;
  if (s.type !== undefined) out.type = s.type;            // Dungeon | Raid | WeeklyDungeon
  if (s.notes !== undefined) out.notes = s.notes;
  if (typeof s.finalStep === 'string') out.finalStep = s.finalStep;
  for (const flag of STEP_FLAGS) {
    if (typeof s[flag] === 'boolean' && s[flag]) out[flag] = true;
  }
  if (Array.isArray(s.bosses)) out.bosses = s.bosses.map(normBoss);
  if (Array.isArray(s.steps)) out.steps = s.steps.map(normStep);
  return out;
}

const normalizedSteps = planner.steps.map(normStep);

// --- write RouteData.lua ---------------------------------------------------
const header = '-- GENERATED by scripts/build-data.mjs — DO NOT EDIT BY HAND.\n' +
  '-- Source: data/planner.json (SimpleArmory).\n\n';
writeFileSync(OUT_ROUTE, header + 'SAMountsRouteData = ' + luaArray(normalizedSteps, '') + '\n');

// --- collect runs (leaves with bosses) -------------------------------------
const runs = [];
const titleCount = new Map();
function collectRuns(steps) {
  for (const s of steps) {
    if (Array.isArray(s.bosses) && s.bosses.length) {
      runs.push({
        title: s.title || '(untitled)',
        type: s.type || '?',
        bosses: s.bosses.map((b) => ({ spellId: Number(b.spellId), mount: b.mount, name: b.name, note: b.note })),
      });
      titleCount.set(s.title, (titleCount.get(s.title) || 0) + 1);
    }
    if (Array.isArray(s.steps)) collectRuns(s.steps);
  }
}
collectRuns(normalizedSteps);

// de-duplicate by title (same-titled runs = same instance -> one Locations entry)
const seen = new Set();
const uniqueRuns = runs.filter((r) => (seen.has(r.title) ? false : (seen.add(r.title), true)));
const dupTitles = [...titleCount.entries()].filter(([, n]) => n > 1).map(([t]) => t);

// --- write Locations skeleton ----------------------------------------------
function skeletonEntry(r) {
  const lines = [];
  lines.push(`  [${luaString(r.title)}] = {`);
  lines.push(`    -- type = ${r.type}`);
  for (const b of r.bosses) {
    const note = b.note ? `  note: ${b.note}` : '';
    lines.push(`    -- boss "${b.name}" -> ${b.mount} (spellId ${b.spellId})${note}`);
  }
  lines.push(`    map = nil, x = nil, y = nil,          -- TODO instance entrance coords (0-100)`);
  lines.push(`    lockout = nil,                        -- TODO exact GetSavedInstanceInfo name`);
  lines.push(`    reqDiff = nil, diffScope = nil,       -- TODO 1/2/23|14/15/16/17|3/4/5/6 ; "dungeon"|"raid"|"legacyRaid"`);
  lines.push(`    encounters = {},                      -- TODO [spellId] = encounterID`);
  lines.push(`  },`);
  return lines.join('\n');
}

const skelHeader = '-- Skeleton generated by scripts/build-data.mjs — fill in by hand.\n' +
  '-- Complete this into SAMounts/Locations.lua (never overwritten by the build).\n\n';
const skelBody = 'SAMountsLocations = {\n' + uniqueRuns.map(skeletonEntry).join('\n') + '\n}\n';
writeFileSync(OUT_SKELETON, skelHeader + skelBody);

// create SAMounts/Locations.lua only if it does not exist yet
if (!existsSync(OUT_LOCATIONS)) {
  writeFileSync(OUT_LOCATIONS, skelHeader + skelBody);
}

// --- report ----------------------------------------------------------------
console.log(`RouteData.lua written: ${normalizedSteps.length} root step(s)`);
console.log(`Runs collected: ${runs.length} (${uniqueRuns.length} unique titles)`);
console.log(`Locations skeleton: ${OUT_SKELETON}`);
console.log(existsSync(OUT_LOCATIONS) ? `Locations.lua: ${OUT_LOCATIONS}` : '  (Locations.lua not created?)');
if (dupTitles.length) {
  console.log(`\nWARN duplicate run titles (${dupTitles.length}) — they will share one Locations entry:`);
  for (const t of dupTitles) console.log(`   - ${t} (x${titleCount.get(t)})`);
}
