#!/usr/bin/env node
// build-mounts.mjs — transform the in-game export (data/mounts-export.lua, produced
// by `/emf gen` then copied here) into our own Lua data files, replacing the
// external SimpleArmory planner. DEV-ONLY: end users get the generated files, never
// the generator or this script.
//
// Produces:
//   EasyMountFarmer/Data/MountsInstances.lua  -> global EasyMountFarmerInstances
//        dungeon / raid / world-boss drops (the ones with an encounterID), tagged
//        with a category and the difficulties they drop on.
//   EasyMountFarmer/Data/MountsWorld.lua      -> global EasyMountFarmerWorld
//        "drop" mounts that are NOT on an instance boss (world rares, treasures…).
//
// Hand-authored trash drops (Ahn'Qiraj tanks, Amani bear) live in Data/ExtraMounts.lua
// and are excluded here by mountID.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import luaparse from 'luaparse';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SRC = join(ROOT, 'data', 'mounts-export.lua');
const OUT_INST = join(ROOT, 'EasyMountFarmer', 'Data', 'MountsInstances.lua');
const OUT_WORLD = join(ROOT, 'EasyMountFarmer', 'Data', 'MountsWorld.lua');

// EJ world-boss "instances" are named after the expansion/continent (frFR dev data).
const WORLD_BOSS_INSTANCES = new Set(['Pandarie', 'Draenor', 'Azeroth']);
// mountIDs handled by hand in ExtraMounts.lua (Ahn'Qiraj tanks + Amani Battle Bear).
const EXTRA_MOUNT_IDS = new Set([110, 117, 118, 119, 120, 400]);

// --- evaluate a luaparse table-literal AST into a plain JS value ---------------
function evalNode(node) {
  switch (node.type) {
    case 'StringLiteral':
      return node.value != null ? node.value : node.raw.slice(1, -1);
    case 'NumericLiteral':
      return node.value;
    case 'BooleanLiteral':
      return node.value;
    case 'NilLiteral':
      return null;
    case 'UnaryExpression':
      return node.operator === '-' ? -evalNode(node.argument) : evalNode(node.argument);
    case 'TableConstructorExpression': {
      const arrayOnly = node.fields.every((f) => f.type === 'TableValue');
      if (arrayOnly) return node.fields.map((f) => evalNode(f.value));
      const obj = {};
      for (const f of node.fields) {
        if (f.type === 'TableKeyString') obj[f.key.name] = evalNode(f.value);
        else if (f.type === 'TableKey') obj[evalNode(f.key)] = evalNode(f.value);
        else obj[obj.__n = (obj.__n || 0) + 1] = evalNode(f.value); // rare positional-in-map
      }
      delete obj.__n;
      return obj;
    }
    default:
      throw new Error('unhandled node: ' + node.type);
  }
}

function readGen() {
  const ast = luaparse.parse(readFileSync(SRC, 'utf8'), { luaVersion: '5.1' });
  for (const stmt of ast.body) {
    if (stmt.type === 'AssignmentStatement'
        && stmt.variables[0]?.type === 'Identifier'
        && stmt.variables[0].name === 'EasyMountFarmerGen') {
      return evalNode(stmt.init[0]);
    }
  }
  throw new Error('EasyMountFarmerGen not found in ' + SRC);
}

// --- strip WoW escape codes from source text -----------------------------------
function cleanSource(s) {
  if (!s) return s;
  return s
    .replace(/\|c[0-9a-fA-F]{8}/g, '')
    .replace(/\|r/g, '')
    .replace(/\|T.-\|t/g, '')
    .replace(/\|T[^|]*\|t/g, '')
    .replace(/\|n/g, ' / ')
    .replace(/\s+/g, ' ')
    .trim();
}

// --- Lua serialization ---------------------------------------------------------
const IDENT = /^[A-Za-z_][A-Za-z0-9_]*$/;
function luaStr(s) {
  return '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '') + '"';
}
function luaVal(v, indent) {
  if (v === null || v === undefined) return 'nil';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'nil';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'string') return luaStr(v);
  if (Array.isArray(v)) {
    if (!v.length) return '{}';
    return '{ ' + v.map((x) => luaVal(x, indent)).join(', ') + ' }';
  }
  const inner = indent + '  ';
  const keys = Object.keys(v);
  const parts = keys.map((k) => `${inner}${IDENT.test(k) ? k : `[${luaStr(k)}]`} = ${luaVal(v[k], inner)}`);
  return '{\n' + parts.join(',\n') + ',\n' + indent + '}';
}
function writeLua(path, global, arr, note) {
  const header = `-- GENERATED by scripts/build-mounts.mjs — DO NOT EDIT BY HAND.\n-- ${note}\n\n`;
  writeFileSync(path, header + `${global} = ` + luaVal(arr, '') + '\n');
}

// --- route ordering: expansion -> zone -> intra-zone nearest-neighbour ---------
// Expansion is the top level because each one has its own capital portal (that's how
// people actually farm). Zones within an expansion share a continent (short flights),
// so we just group by zone; intra-zone we chain by proximity on the (local) entrance
// coords. Cross-zone geographic order isn't meaningful (coords are per-map), so zones
// are ordered by name — cheap and close enough on one continent.
const EXPANSION_ORDER = ['Classic', 'Burning Crusade', 'Wrath of the Lich King', 'Cataclysm',
  'Mists of Pandaria', 'Warlords of Draenor', 'Legion', 'Battle for Azeroth', 'Shadowlands',
  'Dragonflight', 'The War Within', 'Midnight'];
const expIdx = (e) => { const i = EXPANSION_ORDER.indexOf(e); return i < 0 ? 999 : i; };

function nnChain(items) {
  const rem = items.slice();
  if (!rem.length) return [];
  rem.sort((a, b) => (a.x - b.x) || (a.y - b.y));
  const out = [rem.shift()];
  while (rem.length) {
    const last = out[out.length - 1];
    let bi = 0, bd = Infinity;
    for (let i = 0; i < rem.length; i++) {
      const dx = rem[i].x - last.x, dy = rem[i].y - last.y, d = dx * dx + dy * dy;
      if (d < bd) { bd = d; bi = i; }
    }
    out.push(rem.splice(bi, 1)[0]);
  }
  return out;
}

function orderInstances(list) {
  const byExp = {};
  for (const m of list) (byExp[m.expansion] ||= []).push(m);
  const ordered = [];
  for (const exp of Object.keys(byExp).sort((a, b) => expIdx(a) - expIdx(b))) {
    const located = byExp[exp].filter((m) => m.x != null && m.zoneName);
    const noloc = byExp[exp].filter((m) => !(m.x != null && m.zoneName));
    const zones = {};
    for (const m of located) (zones[m.zoneName] ||= []).push(m);
    for (const zn of Object.keys(zones).sort()) ordered.push(...nnChain(zones[zn]));
    noloc.sort((a, b) => (a.mount || '').localeCompare(b.mount || ''));  // world bosses last
    ordered.push(...noloc);
  }
  ordered.forEach((m, i) => { m.order = i + 1; });
  return ordered;
}

// --- transform -----------------------------------------------------------------
const gen = readGen();
const mounts = gen.mounts || [];
const orphans = gen.orphans || [];

const instances = orderInstances(mounts.map((m) => ({
  category: WORLD_BOSS_INSTANCES.has(m.instance) ? 'worldboss' : (m.isRaid ? 'raid' : 'dungeon'),
  expansion: m.expansion,
  continent: m.continent ?? null,
  continentName: m.continentName ?? null,
  zone: m.zone ?? null,
  zoneName: m.zoneName ?? null,
  x: m.x ?? null,
  y: m.y ?? null,
  instance: m.instance,
  journalInstanceID: m.journalInstanceID,
  boss: m.boss ?? null,
  encounterID: m.encounterID ?? null,
  mountID: m.mountID ?? null,
  spellID: m.spellID ?? null,
  itemID: m.itemID ?? null,
  mount: m.mount ?? null,
  faction: m.faction ?? null,
  difficulties: m.difficulties || [],
  diff: m.diff ?? null,
})));

const world = orphans
  .filter((o) => !EXTRA_MOUNT_IDS.has(o.mountID))
  .map((o) => ({ category: 'worldrare', mountID: o.mountID, mount: o.mount, source: cleanSource(o.source) }))
  .sort((a, b) => (a.mount || '').localeCompare(b.mount || ''));

writeLua(OUT_INST, 'EasyMountFarmerInstances', instances,
  'Dungeon / raid / world-boss mount drops (source: in-game Encounter Journal).');
writeLua(OUT_WORLD, 'EasyMountFarmerWorld', world,
  'World "drop" mounts not tied to an instance boss (rares, treasures, world quests…).');

// --- report --------------------------------------------------------------------
const byCat = {};
for (const m of instances) byCat[m.category] = (byCat[m.category] || 0) + 1;
console.log(`instances: ${instances.length} (${Object.entries(byCat).map(([k, n]) => `${k}=${n}`).join(', ')}) -> ${OUT_INST}`);
console.log(`world:     ${world.length} -> ${OUT_WORLD}`);
const unresolved = instances.filter((m) => !m.mountID).map((m) => m.mount || m.itemID);
if (unresolved.length) console.log(`WARN ${unresolved.length} instance mount(s) without mountID: ${unresolved.join(', ')}`);
