#!/usr/bin/env node
// build-data.mjs — convertit le "planner" de SimpleArmory (data/planner.json)
// en données Lua consommables par l'addon.
//
// Produit :
//   MountRoadmap/RouteData.lua          <- table Lua de l'arbre de route (GÉNÉRÉ, ne pas éditer)
//   scripts/Locations.skeleton.lua      <- squelette à remplir à la main (coords/lockout/diff/encounters)
//   MountRoadmap/Locations.lua          <- créé UNIQUEMENT s'il n'existe pas encore (jamais écrasé)
//
// Usage : node scripts/build-data.mjs

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SRC = join(ROOT, 'data', 'planner.json');
const OUT_ROUTE = join(ROOT, 'MountRoadmap', 'RouteData.lua');
const OUT_SKELETON = join(ROOT, 'scripts', 'Locations.skeleton.lua');
const OUT_LOCATIONS = join(ROOT, 'MountRoadmap', 'Locations.lua');

// --- lecture ---------------------------------------------------------------
const planner = JSON.parse(readFileSync(SRC, 'utf8'));
if (!Array.isArray(planner.steps)) {
  throw new Error('planner.json invalide : "steps" manquant');
}

// --- helpers Lua -----------------------------------------------------------
const IDENT = /^[A-Za-z_][A-Za-z0-9_]*$/;

function luaString(s) {
  return '"' + String(s)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '') + '"';
}

function luaKey(k) {
  return IDENT.test(k) ? k : `[${luaString(k)}]`;
}

function luaValue(v, indent) {
  if (v === null || v === undefined) return 'nil';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'nil';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'string') return luaString(v);
  if (Array.isArray(v)) return luaArray(v, indent);
  if (typeof v === 'object') return luaTable(v, indent);
  return 'nil';
}

function luaArray(arr, indent) {
  if (arr.length === 0) return '{}';
  const inner = indent + '  ';
  const parts = arr.map((item) => inner + luaValue(item, inner));
  return '{\n' + parts.join(',\n') + ',\n' + indent + '}';
}

function luaTable(obj, indent) {
  const keys = Object.keys(obj);
  if (keys.length === 0) return '{}';
  const inner = indent + '  ';
  const parts = keys.map((k) => `${inner}${luaKey(k)} = ${luaValue(obj[k], inner)}`);
  return '{\n' + parts.join(',\n') + ',\n' + indent + '}';
}

// --- normalisation d'une étape --------------------------------------------
// On ne garde que les champs utiles à l'addon, et on convertit boss.ID (string)
// en nombre. On préserve la structure imbriquée (steps).
const STEP_FLAGS = ['capital', 'startStep', 'finalStep', 'hearth', 'unavailable', 'boosted'];

function normBoss(b) {
  const out = {};
  if (b.ID !== undefined) out.ID = Number(b.ID);          // mount journal ID
  if (b.mount !== undefined) out.mount = b.mount;
  if (b.name !== undefined) out.name = b.name;            // nom du boss
  if (b.itemId !== undefined) out.itemId = Number(b.itemId);
  if (b.spellId !== undefined) out.spellId = Number(b.spellId);
  if (b.icon !== undefined) out.icon = b.icon;
  if (b.epic !== undefined) out.epic = !!b.epic;
  if (b.note !== undefined) out.note = b.note;
  if (b.isAlliance) out.isAlliance = true;
  if (b.isHorde) out.isHorde = true;
  return out;
}

function normStep(s) {
  const out = {};
  if (s.title !== undefined) out.title = s.title;
  if (s.type !== undefined) out.type = s.type;            // Dungeon | Raid | WeeklyDungeon
  if (s.notes !== undefined) out.notes = s.notes;
  if (typeof s.finalStep === 'string') out.finalStep = s.finalStep;
  for (const f of STEP_FLAGS) {
    if (typeof s[f] === 'boolean' && s[f]) out[f] = true;
  }
  if (Array.isArray(s.bosses)) out.bosses = s.bosses.map(normBoss);
  if (Array.isArray(s.steps)) out.steps = s.steps.map(normStep);
  return out;
}

const normalizedSteps = planner.steps.map(normStep);

// --- écriture RouteData.lua ------------------------------------------------
const header = '-- GENERATED by scripts/build-data.mjs — DO NOT EDIT BY HAND.\n' +
  '-- Source: data/planner.json (SimpleArmory).\n\n';
writeFileSync(OUT_ROUTE, header + 'MountRoadmapRouteData = ' + luaArray(normalizedSteps, '') + '\n');

// --- collecte des runs (feuilles avec bosses) ------------------------------
const runs = [];        // { title, type, bosses:[{spellId, mount, name}] }
const titleCount = new Map();
function collectRuns(steps) {
  for (const s of steps) {
    if (Array.isArray(s.bosses) && s.bosses.length) {
      runs.push({
        title: s.title || '(sans titre)',
        type: s.type || '?',
        bosses: s.bosses.map((b) => ({ spellId: Number(b.spellId), mount: b.mount, name: b.name, note: b.note })),
      });
      titleCount.set(s.title, (titleCount.get(s.title) || 0) + 1);
    }
    if (Array.isArray(s.steps)) collectRuns(s.steps);
  }
}
collectRuns(normalizedSteps);

// dédoublonnage par titre (les runs de même titre = même instance -> une entrée Locations)
const seen = new Set();
const uniqueRuns = runs.filter((r) => (seen.has(r.title) ? false : (seen.add(r.title), true)));

const dupTitles = [...titleCount.entries()].filter(([, n]) => n > 1).map(([t]) => t);

// --- écriture du squelette Locations --------------------------------------
function skeletonEntry(r) {
  const lines = [];
  lines.push(`  [${luaString(r.title)}] = {`);
  lines.push(`    -- type = ${r.type}`);
  for (const b of r.bosses) {
    const note = b.note ? `  note: ${b.note}` : '';
    lines.push(`    -- boss "${b.name}" -> ${b.mount} (spellId ${b.spellId})${note}`);
  }
  lines.push(`    map = nil, x = nil, y = nil,          -- TODO coords entrée instance (0-100)`);
  lines.push(`    lockout = nil,                        -- TODO nom exact GetSavedInstanceInfo`);
  lines.push(`    reqDiff = nil, diffScope = nil,       -- TODO 1/2/23|14/15/16/17|3/4/5/6 ; "dungeon"|"raid"|"legacyRaid"`);
  lines.push(`    encounters = {},                      -- TODO [spellId] = encounterID`);
  lines.push(`  },`);
  return lines.join('\n');
}

const skelHeader = '-- SQUELETTE généré par scripts/build-data.mjs — à remplir à la main.\n' +
  '-- Copiez/complétez vers MountRoadmap/Locations.lua (jamais écrasé par le build).\n\n';
const skelBody = 'MountRoadmapLocations = {\n' + uniqueRuns.map(skeletonEntry).join('\n') + '\n}\n';
writeFileSync(OUT_SKELETON, skelHeader + skelBody);

// crée MountRoadmap/Locations.lua seulement s'il n'existe pas encore
if (!existsSync(OUT_LOCATIONS)) {
  writeFileSync(OUT_LOCATIONS, skelHeader + skelBody);
}

// --- rapport ---------------------------------------------------------------
console.log(`RouteData.lua écrit : ${normalizedSteps.length} étapes racine`);
console.log(`Runs collectés : ${runs.length} (dont ${uniqueRuns.length} titres uniques)`);
console.log(`Squelette Locations : ${OUT_SKELETON}`);
if (!existsSync(OUT_LOCATIONS)) console.log('  (Locations.lua non créé — problème ?)');
else console.log(`Locations.lua : ${OUT_LOCATIONS}`);
if (dupTitles.length) {
  console.log(`\n⚠ Titres de run en double (${dupTitles.length}) — partageront la même entrée Locations :`);
  for (const t of dupTitles) console.log(`   - ${t} (x${titleCount.get(t)})`);
}
